### ISSUE TITLE
借個版面通知一下

### ISSUE THREAD

**Issue by hatelove** [jame2408/EFConsole#1]
hi Jame, 

我是 91。你原先 fork 的那一份 GOOS_Sample 有些版權上的疑慮。麻煩您跟我聯繫一下或請您刪除 fork 的那一份 repository, 麻煩你了，謝謝。

您可以直接回覆這個 issue, 或是在 facebook 上直接 pin 我 IM，感謝。我的Facebook: https://www.facebook.com/hatelove

**Comment by jame2408** [comment]
因近期較忙較晚回覆，已經刪除 fork 的那一份 repository，抱歉造成你的困擾。
